### ISSUE TITLE
Incorrect schema generation for a field when it is nullable and/or has multiple data-types

### ISSUE THREAD

**Issue by SeanCassiere** [elierotenberg/fastify-zod#32]
## Description
This issue is being filed regarding, the resulting OpenAPI document being served to SwaggerUI, being incorrect and not being compliant with the OpenAPI3 specification, in regard to a property having multiple `data-types`, or being `nullable`.

## Scenario
Consider the following basic setup.
```ts
const NameInputSchema = z.object({
  name: z.string().nullable() // or even z.string().or(z.null()) 
});

const models = { NameInputSchema };

// fastify server plugin registration
await register(fastify,  {
  jsonSchemas: buildJsonSchemas(models),
  swaggerOptions: {
    // ...options
  }
})
```
This gets transformed into the following OpenAPI property schemas as such, when using the `buildJsonSchemas(models)` helper:
```jsonc
{
  // others
  "name": {
    "type": [
      "string",
      "null"
    ]
  }
}
```
The above transformation would be correct for JsonSchema, however, it is not compilation with the OpenAPI3 spec.

This transformation is not OpenAPI3 spec compliant for two reasons:

1. because, the OpenAPI specification's [data-types](https://swagger.io/docs/specification/data-models/data-types/) do not include `null`, rather it allows you to make the field null using a `{ nullable: boolean }` prop.

Rather, the transformed/output property should look like this:
```jsonc
{
  // ...others
  "name": {
    "type": "string",
    "nullable": true
  }
}
```
<br />
2. because, when defining multiple/alternate types for the OpenAPI specification, it is meant to be put into an array with either the of the following keys.

* `oneOf`
* `anyOf`

Therefore, for this zod schema:
```ts
const AgeInputSchema = z.object({
  age: z.string().or(z.number()) 
});
```
It should be transformed into:
```jsonc
{
  // ... others
  "age": {
    "oneOf": [
      { "type": "string" },
      { "type": "number" }
    ]
  }
}
```

**Comment by SeanCassiere** [comment]
This is not corrected when using `buildeJsonSchemas(models, { target: 'openApi3' })`, as it prints the following error.
```bash
FastifyError [Error]: Failed building the validation schema for GET: /api/logs, due to error "nullable" cannot be used without "type"
    at Boot.<anonymous> (/Users/seanc/code/simple-logging-server/node_modules/fastify/lib/route.js:359:21)
    at Object.onceWrapper (node:events:627:28)
    at Boot.emit (node:events:525:35)
    at Boot.emit (node:domain:489:12)
    at /Users/seanc/code/simple-logging-server/node_modules/avvio/boot.js:160:12
    at /Users/seanc/code/simple-logging-server/node_modules/avvio/plugin.js:275:7
    at done (/Users/seanc/code/simple-logging-server/node_modules/avvio/plugin.js:200:5)
    at check (/Users/seanc/code/simple-logging-server/node_modules/avvio/plugin.js:224:9)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9) {
  code: 'FST_ERR_SCH_VALIDATION_BUILD',
  statusCode: 500
}
```

**Comment by SeanCassiere** [comment]
Nevermind, please ignore, turns out the crash was happening because of another zod schema `z.any().nullable().optional()`, which works if changed to `z.any().optional()`.
