### ISSUE TITLE
type error when mergeRefs: true

### ISSUE THREAD

**Issue by capaj** [elierotenberg/fastify-zod#6]
```
/home/capaj/work-repos/mindmed/digital/api/node_modules/ajv/lib/ajv.js:481
    throw new Error('schema with key or id "' + id + '" already exists');
          ^
Error: schema with key or id "probeResponse" already exists
    at checkUnique (/home/capaj/work-repos/mindmed/digital/api/node_modules/ajv/lib/ajv.js:481:11)
    at Ajv.addSchema (/home/capaj/work-repos/mindmed/digital/api/node_modules/ajv/lib/ajv.js:136:3)
    at ValidatorCompiler (/home/capaj/work-repos/mindmed/digital/api/node_modules/@fastify/ajv-compiler/index.js:51:9)
    at buildCompilerFromPool (/home/capaj/work-repos/mindmed/digital/api/node_modules/@fastify/ajv-compiler/index.js:19:22)
    at SchemaController.setupValidator (/home/capaj/work-repos/mindmed/digital/api/node_modules/fastify/lib/schema-controller.js:100:56)
    at Boot.<anonymous> (/home/capaj/work-repos/mindmed/digital/api/node_modules/fastify/lib/route.js:311:30)
    at Object.onceWrapper (node:events:639:28)
    at Boot.emit (node:events:532:35)
    at Boot.emit (node:domain:475:12)
    at /home/capaj/work-repos/mindmed/digital/api/node_modules/avvio/boot.js:153:12
```

only happens when I have `mergeRefs: true`.
When I disable it, it works fine.

I have 0.1.0

**Comment by elierotenberg** [comment]
Hi!

As mentionned in #5, I wasn't happy with `mergeRefs` and decided to take another approach. `mergeRefs` options will be removed in 1.0.x.
